### ISSUE TITLE
JACK (+LV2) CV?

### ISSUE THREAD

**Issue by mxmilkiib** [hdavid/ports#1]
The JACK audio system and LV2 plugin format both allow support for CV signals plumbed between apps and [plugins](https://www.youtube.com/watch?v=eMj-q5adAZ4). The metadata mechanism allowing CV was recently added to JACK2 recently along with further CV support in a few JACK clients and LV2 hosts. A method of translating this to and from real world CV would be most adventitious. Some details can be found on [this](https://github.com/cbdevnet/midimonster/issues/30) thread.

**Comment by hdavid** [comment]
hi, this is not planned feature. Ports interfaces with a specific chip and was not intended to drive audio. but the code is open source, feel free to have a go ! :)
